### ISSUE TITLE
Add messaging if the map does not contain any trace configurations

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#105]
![image](https://user-images.githubusercontent.com/50338557/135177526-c38f296e-019a-486a-874f-e6613143717b.png)

**Comment by avezina** [comment]
String could be: 
" This web map does not support tracing the Utility Network. Publish a web map with shared Trace Configurations. "

**Comment by avezina** [comment]
Could display the warning in the Inputs tab the same way we are showing info in Results tabwhen it's empty
![image](https://user-images.githubusercontent.com/50338557/142054799-fe5d5545-d9ac-42a4-b9af-b80adeb7184f.png)

**Comment by previnWong** [comment]
installed in
https://devtopia.esri.com/WebGIS/arcgis-js-api/tree/prev8048/utilitynetworktrace_111621

place it by itself, no tabs, since with TC, the widget is useless, no need to display tabs.
![image](https://user-images.githubusercontent.com/11183838/142289756-68ee78f7-bfa1-490d-8d80-a63c50f83bc9.png)

**Comment by avezina** [comment]
Tested with map that doesn't have TC http://dev0016770.esri.com/arcgis-js-api/test-apps/traceTest.html?webmap=3a438bab839a427ebac9f6ca4f490af0&portal=https://avezina2.esri.com/portal
