### ISSUE TITLE
UI - Need a better way to break up Add Location/Barrier

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#43]
It is hard to focus on the different sections.  We need a way to break up the Add Barrier/ Add Location sections
![image](https://user-images.githubusercontent.com/2707285/126545830-94096186-def4-4474-86b9-bc75414ff7ee.png)

**Comment by previnWong** [comment]
@MikeMillerGIS , yes, one of the todos is to switch that to use blocks like the trace selection and run sections.  Didn't use blocks because they there was an issue with left sides action (not in blocks) and embedded accordians with left side action (for terminals).  Image shown was proposed by Alan.  But since then, Alan and I omitted the left side action for terminals so I can ditch accordion I think I might be able to use blocks again.  (terminals will be accessible from the options ellipse)

**Comment by avezina** [comment]
Blocks implemented
![image](https://user-images.githubusercontent.com/50338557/127403871-5d664414-077c-4337-9e78-e9fa9b3891af.png)
